# docker-compose.yml

services:
  analysis-service:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - data-volume:/user/eso_analysis/data
  test-service:
  # will only start if specified with --profile option with docker compose
    profiles:
      - testing
    build:
      context: .
      dockerfile: Dockerfile  #TODO separate dev container build
    depends_on:
      - analysis-service
    command: >
      sh -c 'python -m pytest test -vv'

volumes:
  data-volume:
    name: "eso_database"